#include "vemu/compiler.h"
#include "vemu/tty.h"
#include "vemu/vga.h"
#include <stdio.h>
#include <string.h>

char *make_cs_color(char *txt, vga_entry_t entry) {
	switch(entry.bg) {
		case 0x00: sprintf(txt, "Console.BackgroundColor = ConsoleColor.Black;"); break;
		case 0x01: sprintf(txt, "Console.BackgroundColor = ConsoleColor.DarkBlue;"); break;
		case 0x02: sprintf(txt, "Console.BackgroundColor = ConsoleColor.DarkGreen;"); break;
		case 0x03: sprintf(txt, "Console.BackgroundColor = ConsoleColor.DarkCyan;"); break;
		case 0x04: sprintf(txt, "Console.BackgroundColor = ConsoleColor.DarkRed;"); break;
		case 0x05: sprintf(txt, "Console.BackgroundColor = ConsoleColor.DarkMagenta;"); break;
		case 0x06: sprintf(txt, "Console.BackgroundColor = ConsoleColor.DarkYellow;"); break;
		case 0x07: sprintf(txt, "Console.BackgroundColor = ConsoleColor.Gray;"); break;
		case 0x08: sprintf(txt, "Console.BackgroundColor = ConsoleColor.DarkGray;"); break;
		case 0x09: sprintf(txt, "Console.BackgroundColor = ConsoleColor.Blue;"); break;
		case 0x0A: sprintf(txt, "Console.BackgroundColor = ConsoleColor.Green;"); break;
		case 0x0B: sprintf(txt, "Console.BackgroundColor = ConsoleColor.Cyan;"); break;
		case 0x0C: sprintf(txt, "Console.BackgroundColor = ConsoleColor.Red;"); break;
		case 0x0D: sprintf(txt, "Console.BackgroundColor = ConsoleColor.Magenta;"); break;
		case 0x0E: sprintf(txt, "Console.BackgroundColor = ConsoleColor.Yellow;"); break;
		case 0x0F: sprintf(txt, "Console.BackgroundColor = ConsoleColor.White;"); break;
	}
	switch(entry.fg) {
		case 0x00: strcat(txt, " Console.ForegroundColor = ConsoleColor.Black;"); break;
		case 0x01: strcat(txt, " Console.ForegroundColor = ConsoleColor.DarkBlue;"); break;
		case 0x02: strcat(txt, " Console.ForegroundColor = ConsoleColor.DarkGreen;"); break;
		case 0x03: strcat(txt, " Console.ForegroundColor = ConsoleColor.DarkCyan;"); break;
		case 0x04: strcat(txt, " Console.ForegroundColor = ConsoleColor.DarkRed;"); break;
		case 0x05: strcat(txt, " Console.ForegroundColor = ConsoleColor.DarkMagenta;"); break;
		case 0x06: strcat(txt, " Console.ForegroundColor = ConsoleColor.DarkYellow;"); break;
		case 0x07: strcat(txt, " Console.ForegroundColor = ConsoleColor.Gray;"); break;
		case 0x08: strcat(txt, " Console.ForegroundColor = ConsoleColor.DarkGray;"); break;
		case 0x09: strcat(txt, " Console.ForegroundColor = ConsoleColor.Blue;"); break;
		case 0x0A: strcat(txt, " Console.ForegroundColor = ConsoleColor.Green;"); break;
		case 0x0B: strcat(txt, " Console.ForegroundColor = ConsoleColor.Cyan;"); break;
		case 0x0C: strcat(txt, " Console.ForegroundColor = ConsoleColor.Red;"); break;
		case 0x0D: strcat(txt, " Console.ForegroundColor = ConsoleColor.Magenta;"); break;
		case 0x0E: strcat(txt, " Console.ForegroundColor = ConsoleColor.Yellow;"); break;
		case 0x0F: strcat(txt, " Console.ForegroundColor = ConsoleColor.White;"); break;
	}
	return txt;
}


void compile_csharp(FILE *in, FILE *out) {
	fprintf(out,
"// Generated by VEMU.\n\nusing System;\n\n"
"class Program {\n"
"\tstatic void Main(string[] args) {\n");
	char txt[128];
	vga_entry_t entry1;
	vga_entry_t entry2;
	for(size_t y=0; y < VGA_HEIGHT; y++) {
		for(size_t x=0; x < VGA_WIDTH; x++) {
			/*
			 * (&txt) = warning: passing argument 1 of 'make_char' from incompatible pointer type
			 * (&txt[0]) = no compiler warning
			 */
			entry2 = vga_read_entry(
				tty_buf[vga_get_index(x, y)]
			);
			int ch = (entry2.ch < 32 ? ' ' : entry2.ch);
			if((entry1.bg != entry2.bg) || (entry1.fg != entry2.fg)) {
				fprintf(out, "\t\t%s Console.Write((char)%d);\n", make_cs_color((&txt[0]), entry2), ch);
			} else {
				fprintf(out, "\t\tConsole.Write((char)%d);\n", ch);
			}
			entry1 = entry2;
		}
		fprintf(out, "\t\tConsole.WriteLine();\n");
	}
	fprintf(out, "\t}\n}");
}

void dump_display(FILE *out) {
	char txt[128];
	vga_entry_t entry;
	for(size_t y=0; y < VGA_HEIGHT; y++) {
		for(size_t x=0; x < VGA_WIDTH; x++) {
			entry = vga_read_entry( tty_buf[ vga_get_index(x, y) ] );
			fprintf("%c%c", entry.color, entry.ch);
		}
	}
}
