name: Build

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    ubuntu-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: chmod +x build.sh && bash ./build.sh
            - uses: actions/checkout@v3
            - name: Deploy
              with:
                name: Linux Executables
                path: bin/**
    windows-build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: chmod +x build.sh && bash ./build.sh
            - uses: actions/checkout@v3
            - name: Deploy
              
              with:
                name: Windows Executables
                path: bin
