name: Build

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    ubuntu-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: chmod +x build.sh && bash ./build.sh
            - name: Linux Upload
              uses: actions/upload-artifact@v3
              with:
                name: Linux Executables
                path: bin/**
            - name: Build Python bindings
              run: chmod +x build-python-bindings.sh && bash ./build-python-bindings.sh
            - name: Upload Python bindings
              uses: actions/upload-artifact@v3
              with:
                name: Python Bindings
                path: bindings/python-bindings/dist/**
    windows-build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: chmod +x build.sh && bash ./build.sh
            - name: Windows Upload
              uses: actions/upload-artifact@v3
              with:
                name: Windows Executables
                path: bin\**
